### ISSUE TITLE
HaskellNet fails when trying to install using Cabal and GHC 7.4.2 on Windows

### ISSUE THREAD

**Issue by rouanvd** [qnikst/HaskellNet#6]
I am trying to use HaskellNet, but it fails when Cabal starts building it with the following error:

Downloading HaskellNet-0.3...
Configuring HaskellNet-0.3...
Building HaskellNet-0.3...
Preprocessing library HaskellNet-0.3...

src\Network\HaskellNet\IMAP.hs:1:1:
    Ambiguous module name `Prelude':
      it was found in multiple packages: base haskell98-2.0.0.1
cabal.exe: Error: some packages failed to install:
HaskellNet-0.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by qnikst** [comment]
Fixed in 0.4 and released on Hackage on 2014-10-07.
