### ISSUE TITLE
Dependency base64-string gives wrong results

### ISSUE THREAD

**Issue by ChristophP** [qnikst/HaskellNet#61]
Recently I discovered that SMTP logins were failing for me. The reason turned out to be a buggy base64 encoding. The encode function of the `base64-string` package version 0.2 has the following behavior:
```
encode "d36e9aaabaa50295b02a1ca3e1b77bef-c27bf672-1e1d6387"

Gives "ZDM2ZTlhYWFiYWE1MDI5NWIwMmExY2EzZTFiNzdiZWYtYzI3YmY2NzItMWUxZDYz\nODc="

Expected
"ZDM2ZTlhYWFiYWE1MDI5NWIwMmExY2EzZTFiNzdiZWYtYzI3YmY2NzItMWUxZDYzODc="
as given by any other base64 encoder I have tried (for example this one https://www.base64encode.org/)
```
Tested on Ubuntu, and inside docker.
I am using the stack resolver 13.14 with HaskellNet 0.5.1

*To be clear:* The actual bug is in the dependency `base64-string` not `HaskellNet` itself. But `HaskellNet` should probably switch to use something that base64 encodes correctly in this use case.

**Comment by dminuoso** [comment]
The standard SMTP Service Extension for Authentication requires the Base64 encoding to follow RFC 4648. That behavior you observed in base64-string is compliant with RFC 4648.

Your mail server is apparently not compliant, file a bug with them.

**Comment by dminuoso** [comment]
I'll conjure up a fix later today.

**Comment by dminuoso** [comment]
As a temporary workaround you could use
```
source-repository-package
  type: git
  location: https://github.com/dminuoso/HaskellNet.git
  tag: 73bf47e9e4ee7ec18da0da2b23a18d4e4baa8485
```

until I reach the maintainer of base64-string.

**Comment by ChristophP** [comment]
Great. Thanks for looking into this. I tried reaching the maintainer of base64-string back when I discovered the issue. I tried via email since I could not find a repository but without any luck. Hopefully you'll be able to get his/her attention.

**Comment by tim2CF** [comment]
I have the same issue
