### ISSUE TITLE
SMTP with TLS documentation is inadaquate

### ISSUE THREAD

**Issue by rohshall** [qnikst/HaskellNet#7]
I am raising this issue just to point out that it is not clear from the documentation how to use SMTP with TLS. Since, most commercial third-party SMTP services like gmail use TLS, I think it is important for the users to know how to do that using HaskellNet. Let me know whether the support is already there. I would love to chime in and work on this issue.

**Comment by lemol** [comment]
Now with 645dd1c, the SMTP module's documentation includes a reference to HaskellNet-SSL for TLS/SSL connections.

**Comment by qnikst** [comment]
I've improved documentation a bit more, I hope it's good now.
